<?php

namespace PaynetEasy\PaynetEasyApi\PaymentData;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-23 at 12:06:49.
 */
class QueryConfigTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var QueryConfig
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new QueryConfig;
    }

    public function testSetGatewayUrl()
    {
        $this->object->setGatewayUrl('sandbox',     QueryConfig::GATEWAY_MODE_SANDBOX);
        $this->object->setGatewayUrl('production',  QueryConfig::GATEWAY_MODE_PRODUCTION);

        $this->assertEquals('sandbox', $this->object->getGatewayUrlSandbox());
        $this->assertEquals('production', $this->object->getGatewayUrlProduction());
    }

    public function testGetGatewayUrl()
    {
        $this->object->setGatewayUrlSandbox('sandbox');
        $this->object->setGatewayUrlProduction('production');

        $this->object->setGatewayMode(QueryConfig::GATEWAY_MODE_SANDBOX);
        $this->assertEquals('sandbox', $this->object->getGatewayUrl());

        $this->object->setGatewayMode(QueryConfig::GATEWAY_MODE_PRODUCTION);
        $this->assertEquals('production', $this->object->getGatewayUrl());
    }

    /**
     * @expectedException \RuntimeException
     * @expectedExceptionMessage End point group has been already set. You can set either end point or end point group.
     */
    public function testSetEndPointIfEndPointGroupExists() {
        $this->object->setEndPointGroup(121);
        $this->object->setEndPoint(121);
    }

    /**
     * @expectedException \RuntimeException
     * @expectedExceptionMessage End point has been already set. You can set either end point or end point group.
     */
    public function testSetEndPointGroupIfEndPointExists() {
        $this->object->setEndPoint(121);
        $this->object->setEndPointGroup(121);
    }
}
