<?php

namespace PaynetEasy\Paynet\Query;

use PaynetEasy\Paynet\Utils\Validator;
use PaynetEasy\Paynet\OrderData\OrderInterface;

class TransferByRefQuery extends AbstractQuery
{
    /**
     * {@inheritdoc}
     */
    static protected $requestFieldsDefinition = array
    (
        // mandatory
        array('client_orderid',             'clientOrderId',                        true,   '#^[\S\s]{1,128}$#i'),
        array('amount',                     'amount',                               true,   '#^[0-9\.]{1,11}$#i'),
        array('currency',                   'currency',                             true,   '#^[A-Z]{1,3}$#i'),
        array('ipaddress',                  'ipAddress',                            true,   Validator::IP),
        array('destination-card-ref-id',    'recurrentCardFrom.cardReferenceId',    true,   '#^[\S\s]{1,20}$#i'),
        // optional
        array('order_desc',                 'description',                          false,  '#^[\S\s]{1,125}$#i'),
        array('source-card-ref-id',         'recurrentCardFrom.cardReferenceId',    false,  '#^[\S\s]{1,20}$#i'),
        array('cvv2',                       'recurrentCardFrom.cvv2',               false,  '#^[\S\s]{1,20}$#i'),
        // generated
        array('control',                    null,                                   true,    null),
        // from config
        array('login',                      null,                                   true,    null),
        array('redirect_url',               null,                                   false,   null),
        array('server_callback_url',        null,                                   false,   null)
    );

    /**
     * {@inheritdoc}
     */
    protected function createControlCode(OrderInterface $order)
    {
        // Checksum generated by SHA-1.
        // This is SHA-1 checksum of the concatenation
        // login + client_orderid + source-card-ref-id + destination-card-ref-id +
        // amount_in_cents + currency + merchant_control
        return sha1
        (
            $this->config['login'] .
            $order->getClientOrderId() .
            $order->getRecurrentCardFrom()->getCardReferenceId() .
            $order->getRecurrentCardTo()->getCardReferenceId() .
            $order->getAmountInCents() .
            $order->getCurrency() .
            $this->config['control']
        );
    }
}