<?php

namespace PaynetEasy\PaynetEasyApi\Callback;

use PaynetEasy\PaynetEasyApi\Transport\CallbackResponse;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-19 at 14:39:15.
 */
class CallbackFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CallbackFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CallbackFactory;
    }

    public function testGetCallback()
    {
        $this->assertInstanceOf('PaynetEasy\PaynetEasyApi\Callback\CustomerReturnCallback',
                                $this->object->getCallback('customer_return'));

        $this->assertInstanceOf('PaynetEasy\PaynetEasyApi\Callback\FakeCallback',
                                $this->object->getCallback('fake'));

        $saleCallback = $this->object->getCallback('sale');

        $this->assertInstanceOf('PaynetEasy\PaynetEasyApi\Callback\PaynetEasyCallback', $saleCallback);
        $this->assertEquals('sale', $this->readAttribute($saleCallback, 'callbackType'));
    }

    /**
     * @expectedException RuntimeException
     * @expectedExceptionMessage Unknown callback class 'PaynetEasy\PaynetEasyApi\Callback\UnknownCallback' for callback with type 'unknown'
     */
    public function testGetQueryWithUnknownClass()
    {
        $this->object->getCallback('unknown');
    }

    /**
     * @expectedException RuntimeException
     * @expectedExceptionMessage Callback class 'PaynetEasy\PaynetEasyApi\Callback\NotcallbackCallback' does not implements 'PaynetEasy\PaynetEasyApi\Callback\CallbackInterface' interface
     */
    public function testGetQueryWithNotCallbackClass()
    {
        $this->object->getCallback('notcallback');
    }
}
