<?php

namespace PaynetEasy\PaynetEasyApi\Query;

use PaynetEasy\PaynetEasyApi\PaymentData\Payment;
use PaynetEasy\PaynetEasyApi\PaymentData\BillingAddress;
use PaynetEasy\PaynetEasyApi\PaymentData\Customer;
use PaynetEasy\PaynetEasyApi\PaymentData\CreditCard;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-12 at 15:13:43.
 */
class SaleQueryTest extends QueryTestPrototype
{
    /**
     * @var SaleQuery
     */
    protected $object;

    /**
     * @var \PaynetEasy\PaynetEasyApi\PaymentData\Payment
     */
    protected $payment;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SaleQuery($this->getConfig());
    }

    public function testCreateRequestProvider()
    {
        return array(array
        (
            sha1
            (
                self::END_POINT .
                self::CLIENT_PAYMENT_ID .
                '99' .                          // amount
                'vass.pupkin@example.com' .     // customer email
                self::SIGN_KEY
            )
        ));
    }

    public function testProcessResponseDeclinedProvider()
    {
        return array(array(array
        (
            'type'              => 'async-response',
            'status'            => 'filtered',
            'paynet-order-id'   =>  self::PAYNET_PAYMENT_ID,
            'merchant-order-id' =>  self::CLIENT_PAYMENT_ID,
            'serial-number'     =>  md5(time()),
            'error-message'     => 'test filtered message',
            'error-code'        => '8876'
        )));
    }

    public function testProcessResponseProcessingProvider()
    {
        return array(array(array
        (
            'type'              => 'async-response',
            'status'            => 'processing',
            'paynet-order-id'   =>  self::PAYNET_PAYMENT_ID,
            'merchant-order-id' =>  self::CLIENT_PAYMENT_ID,
            'serial-number'     => md5(time())
        )));
    }

    public function testProcessResponseErrorProvider()
    {
        return array(
        array(array
        (
            'type'              => 'async-response',
            'status'            => 'error',
            'paynet-order-id'   =>  self::PAYNET_PAYMENT_ID,
            'merchant-order-id' =>  self::CLIENT_PAYMENT_ID,
            'serial-number'     =>  md5(time()),
            'error-message'     => 'test error message',
            'error-code'        => '2'
        )),
        array(array
        (
            'type'              => 'validation-error',
            'serial-number'     =>  md5(time()),
            'error-message'     => 'validation-error message',
            'error-code'        => '1000'
        )),
        array(array
        (
            'type'              => 'error',
            'error-message'     => 'test type error message',
            'error-code'        => '5'
        )));
    }

    protected function getPayment()
    {
        return new Payment(array
        (
            'paynet_payment_id'     =>  self::PAYNET_PAYMENT_ID,
            'client_payment_id'     =>  self::CLIENT_PAYMENT_ID,
            'description'           => 'This is test payment',
            'amount'                =>  0.99,
            'currency'              => 'USD',
            'site_url'              => 'http://example.com',
            'customer'              => new Customer(array
            (
                'first_name'            => 'Vasya',
                'last_name'             => 'Pupkin',
                'email'                 => 'vass.pupkin@example.com',
                'ip_address'            => '127.0.0.1',
                'birthday'              => '112681',
            )),
            'billing_address'       => new BillingAddress(array
            (
                'country'               => 'US',
                'state'                 => 'TX',
                'city'                  => 'Houston',
                'first_line'            => '2704 Colonial Drive',
                'zip_code'              => '1235',
                'phone'                 => '660-485-6353',
                'cell_phone'            => '660-485-6353'
            )),
            'credit_card'           => new CreditCard(array
            (
                'card_printed_name'     => 'Vasya Pupkin',
                'credit_card_number'    => '4485 9408 2237 9130',
                'expire_month'          => '12',
                'expire_year'           => '14',
                'cvv2'                  => '084'
            ))
        ));
    }
}
