<?php

namespace PaynetEasy\Paynet\Utils;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-20 at 17:28:10.
 */
class ValidatorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @dataProvider testValidateByRuleProvider
     */
    public function testValidateByRule($value, $rule, $expectedResult)
    {
        $actualResult = Validator::validateByRule($value, $rule, false);

        if ($expectedResult === true)
        {
            $this->assertTrue($actualResult);
        }
        else
        {
            $this->assertFalse($actualResult);
        }
    }

    public function testValidateByRuleProvider()
    {
        return array(
        array
        (
            'test@mail.com',
            Validator::EMAIL,
            true
        ),
        array
        (
            'test[a]mail.com',
            Validator::EMAIL,
            false
        ),
        array
        (
            '127.0.0.1',
            Validator::IP,
            true
        ),
        array
        (
            '260.0.0.1',
            Validator::IP,
            false
        ),
        array
        (
            'http://site.com',
            Validator::URL,
            true
        ),
        array
        (
            'site.com',
            Validator::URL,
            false
        ),
        array
        (
            'site-com',
            Validator::URL,
            false
        ),
        array
        (
            '1',
            Validator::MONTH,
            true
        ),
        array
        (
            '12',
            Validator::MONTH,
            true
        ),
        array
        (
            '13',
            Validator::MONTH,
            false
        ),
        array
        (
            '0',
            Validator::MONTH,
            false
        ),
        array
        (
            'str',
            Validator::MONTH,
            false
        ),
        array
        (
            'US',
            '#^[A-Z]{1,2}$#',
            true
        ),
        array
        (
            'USA',
            '#^[A-Z]{1,2}$#',
            false
        ));
    }
}
