<?php

namespace PaynetEasy\PaynetEasyApi\Utils;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-20 at 14:08:33.
 */
class StringTest extends \PHPUnit_Framework_TestCase
{
    public function testCamelize()
    {
        $this->assertEquals('CamalCaseString', String::camelize('camal-case-string'));
    }

    public function testUncamelize()
    {
        $this->assertEquals('camal-case-string', String::uncamelize('CamalCaseString', '-'));
    }
}
