<?php

namespace PaynetEasy\Paynet\Queries;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-11 at 16:41:48.
 */
class AbstractQueryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ConcreteQuery
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConcreteQuery(array());
    }

    /**
     * @covers PaynetEasy\Paynet\Queries\AbstractQuery::setApiMethod
     */
    public function testSetApiMethod()
    {
        $this->object->setApiMethod('GetCardInfoQuery');
        $this->assertEquals('get-card-info', $this->object->method);

        $this->object->setApiMethod('ReturnQuery');
        $this->assertEquals('return', $this->object->method);
    }
}

class ConcreteQuery extends AbstractQuery
{
    public $method;

    public function __construct(array $config = array())
    {
    }

    public function setApiMethod($class)
    {
        parent::setApiMethod($class);
    }
}