<?php

namespace PaynetEasy\Paynet\Response;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-08 at 14:17:10.
 */
class CallbackResultTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CallbackResult
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CallbackResult;
    }

    /**
     * @covers PaynetEasy\Paynet\Response\CallbackResult::type
     */
    public function testTypeSuccess()
    {
        $this->object->exchangeArray(array('type' => 'chargeback'));
        $this->assertEquals('chargeback', $this->object->type());
    }

    /**
     * @covers PaynetEasy\Paynet\Response\CallbackResult::type
     * @expectedException \PaynetEasy\Paynet\Exception\CallbackException
     */
    public function testTypeWithError()
    {
        $this->object->exchangeArray(array('type' => 'async-response'));
        $this->object->type();
    }
}
