<?php

namespace PaynetEasy\Paynet\Workflow;

use PaynetEasy\Paynet\OrderData\RecurrentCard;

/**
 * Test class for MakeRebill.
 * Generated by PHPUnit on 2012-06-21 at 14:57:19.
 */
class MakeRebillTest extends SaleTest
{
    const     CARD_REF_ID       = '5588943';

    /**
     * Test class
     * @var string
     */
    protected $class            = 'MakeRebillWorkflow';

    public function getTestData()
    {
        list($customer, $card, $order) = parent::getTestData();

        return array($customer, new RecurrentCard(self::CARD_REF_ID), $order);
    }
}

?>
