<?php

namespace PaynetEasy\Paynet\Workflow;

use PaynetEasy\Paynet\Transport\PaynetClient;
use PaynetEasy\Paynet\Queries\QueryFactory;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-15 at 16:43:36.
 */
class WorkflowFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var WorkflowFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new WorkflowFactory(new PaynetClient('_'), new QueryFactory);
    }

    /**
     * @covers PaynetEasy\Paynet\Workflow\WorkflowFactory::getWorkflow
     */
    public function testGetWorkflow()
    {
        $this->assertInstanceOf('PaynetEasy\Paynet\Workflow\MakeRebillWorkflow',
                                $this->object->getWorkflow('make-rebill'));

        $this->assertInstanceOf('PaynetEasy\Paynet\Workflow\SaleWorkflow',
                                $this->object->getWorkflow('sale'));
    }
}
