<?php

namespace PaynetEasy\PaynetEasyApi\Utils;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-20 at 14:37:44.
 */
class PropertyAccessorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @dataProvider testGetValueProvider
     */
    public function testGetValue($propertyPath, $expectedValue, $failOnError = true)
    {
        $actualValue = PropertyAccessor::getValue(new TestObject, $propertyPath, $failOnError);

        $this->assertEquals($expectedValue, $actualValue);
    }

    public function testGetValueProvider()
    {
        return array(
        array
        (
            'testProperty',
            'test'
        ),
        array
        (
            'testObject.testProperty',
            'test'
        ),
        array
        (
            'testProperty.testProperty',
            null,
            false
        ),
        array
        (
            'unknownProperty',
            null,
            false
        ));
    }
}

class TestObject
{
    protected $testProperty = 'test';

    protected $testObject;

    protected $emptyProperty;

    public function getTestProperty()
    {
        return $this->testProperty;
    }

    public function getTestObject()
    {
        if (!is_object($this->testObject))
        {
            $this->testObject = new static;
        }

        return $this->testObject;
    }

    public function getEmptyProperty()
    {
        return $this->emptyProperty;
    }
}