<?php

namespace PaynetEasy\Paynet\Query;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-11 at 17:21:40.
 */
class QueryFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var QueryFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new QueryFactory;
    }

    /**
     * @covers PaynetEasy\Paynet\Query\QueryFactory::getQuery
     */
    public function testGetQuery()
    {
        $config = array
        (
            'login'     => '_',
            'end_point' => '_',
            'control'   => '_'
        );

        $this->assertInstanceOf('PaynetEasy\Paynet\Query\CreateCardRefQuery',
                                $this->object->getQuery('create-card-ref', $config));

        $this->assertInstanceOf('PaynetEasy\Paynet\Query\ReturnQuery',
                                $this->object->getQuery('return', $config));
    }
}
