<?php

namespace PaynetEasy\Paynet\Callback;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-19 at 13:00:53.
 */
class AbstractCallbackTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ConcreteCallback
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConcreteCallback();
    }

    public function testSetCallbackType()
    {
        $this->object->setCallbackType('PaynetEasy\Paynet\Callback\ConcreteCallback');
        $this->assertEquals('concrete', $this->object->callbackType);
    }
}

class ConcreteCallback extends AbstractCallback
{
    public $callbackType;

    public function __construct()
    {
    }

    public function setCallbackType($class)
    {
        parent::setCallbackType($class);
    }
}