<?php

namespace PaynetEasy\Paynet\Transport;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-25 at 15:51:46.
 */
class GatewayClientTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var GatewayClient
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new GatewayClient('https://qa.clubber.me/paynet/api/v2/');
    }

    public function testMakeRequest()
    {
        $request = new Request(array
        (
            'client_orderid'    => 2121
        ));

        $request->setApiMethod('sale');
        $request->setEndPoint(121);

        $response = $this->object->makeRequest($request);

        $this->assertEquals('validation-error', $response->getType());
    }
}
