<?php

namespace PaynetEasy\PaynetEasyApi\Transport;

use \ReflectionMethod;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-06 at 15:21:28.
 */
class ResponseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Response
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Response;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testIsError()
    {
        $this->object->exchangeArray(array('type' => 'validation-error'));
        $this->assertTrue($this->object->isError());

        $this->object->exchangeArray(array('type' => 'error'));
        $this->assertTrue($this->object->isError());

        $this->object->exchangeArray(array('type' => 'async-response', 'status' => 'error'));
        $this->assertTrue($this->object->isError());

        $this->object->exchangeArray(array('type' => 'async-response', 'status' => 'approved'));
        $this->assertFalse($this->object->isError());
    }

    public function testIsProcessing()
    {
        $this->object->exchangeArray(array('status' => 'processing'));
        $this->assertTrue($this->object->isProcessing());

        $this->object->exchangeArray(array('type' => 'async-response'));
        $this->assertTrue($this->object->isProcessing());

        $this->object->exchangeArray(array('status' => 'error'));
        $this->assertFalse($this->object->isProcessing());

        $this->object->exchangeArray(array('type' => 'error'));
        $this->assertFalse($this->object->isProcessing());
    }

    public function testIsDeclined()
    {
        $this->assertFalse($this->object->isDeclined());

        $this->object->exchangeArray(array('status' => 'filtered'));
        $this->assertTrue($this->object->isDeclined());
    }

    public function testGetAnyKey()
    {
        $method = new ReflectionMethod('PaynetEasy\PaynetEasyApi\Transport\Response', 'getAnyKey');
        $method->setAccessible(true);

        $this->object->exchangeArray(array('first-key' => null, 'first_key' => 2));

        $this->assertEquals(2, $method->invoke($this->object, array('first-key', 'first_key')));
        $this->assertEquals(2, $method->invoke($this->object, array('first_key', 'firstkey')));
        $this->assertNull($method->invoke($this->object, array('first', 'firstkey')));
    }

    public function testGetValue()
    {
        $method = new ReflectionMethod('PaynetEasy\PaynetEasyApi\Transport\Response', 'getValue');
        $method->setAccessible(true);

        $this->object->exchangeArray(array('first-key' => 1, 'first_key' => 2));

        $this->assertEquals(2, $method->invoke($this->object, 'first_key'));
        $this->assertNull($method->invoke($this->object, 'first'));
    }
}
